# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '10'
inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
#  pod 'LYNetManager', :path => '../'
  # Pods for Example
pod 'AFNetworking', '~> 4.0.1'
pod 'YYCache', '~> 1.0.4'
pod 'MJRefresh','3.2.0'
pod 'Masonry', '1.1.0'
pod 'MBProgressHUD','1.1.0'
pod 'MJExtension', '3.3.0'
pod 'lottie-ios', '2.5.3'

end
